#!/usr/bin/env bash
# Self-test for release-notes-status.sh body classification — no network.
#
# Pins the two shapes that must be recognised as "not finished", because both
# render on GitHub exactly like a finished release and are therefore invisible
# to review: the auto-generated "## Changes" PR-title list, and the CI stub
# body ("see CHANGELOG.md for details").
#
# Also pins the false positive found while building it: the harvest script's
# own header line contains "@mention each INLINE at their change", so extracting
# credits without dropping comment lines invents a contributor called "@mention"
# and reports every finished release as missing them.
set -uo pipefail

fail=0
check() { # check <name> <expected> <actual>
  if [ "$2" = "$3" ]; then
    printf 'ok   - %s\n' "$1"
  else
    printf 'FAIL - %s\n       expected: [%s]\n       actual:   [%s]\n' "$1" "$2" "$3"
    fail=1
  fi
}

# --- the auto-generated shape -------------------------------------------------
is_autogenerated() { # <body>
  local body="$1" n
  printf '%s' "$body" | grep -qE '^## (Changes|What'"'"'s Changed)$' || { echo 0; return; }
  n=$(printf '%s' "$body" | sed -n '/^## \(Changes\|What'"'"'s Changed\)$/,/^## /p' \
      | grep -cE '^- .*\(#[0-9]+\)$' || true)
  [ "${n:-0}" -ge 2 ] && echo 1 || echo 0
}

ci_body='## Changes
- chore: release v0.13.0 (#231)
- feat(secret): shared catalogue (#230)

## Installation'
check "CI PR-title list is autogenerated"      1 "$(is_autogenerated "$ci_body")"

narrative='## Highlights

Two pull requests, one theme. Fixed by @alice in #230.

## Installation'
check "narrative body is not autogenerated"    0 "$(is_autogenerated "$narrative")"

# A narrative that merely *mentions* a PR must not trip the heuristic.
prose='## Highlights

The rotation fix (#284) landed here.

## Installation'
check "prose citing one PR is not autogenerated" 0 "$(is_autogenerated "$prose")"

# --- the CI stub --------------------------------------------------------------
is_stub() { printf '%s' "$1" | grep -qiE 'see CHANGELOG\.md for details' && echo 1 || echo 0; }
check "CI stub body detected"                  1 "$(is_stub 'Release v1.2.3 — see CHANGELOG.md for details')"
check "narrative is not a stub"                0 "$(is_stub "$narrative")"

# --- credit extraction --------------------------------------------------------
# Mirrors the pipeline in release-notes-status.sh: drop the harvest header
# before extracting @mentions.
extract_people() { printf '%s' "$1" | grep -v '^#' | grep -oE '@[A-Za-z0-9-]+' | sort -u | tr '\n' ' '; }

harvest_output='# Contributors in v1..v2 — @mention each INLINE at their change (do not paste as a section):
code authors: @alice @bob'
check "harvest header does not become a person" "@alice @bob " "$(extract_people "$harvest_output")"

# --- hand-written Contributors section ----------------------------------------
has_section() { printf '%s' "$1" | grep -qiE '^#+ *Contributors' && echo 1 || echo 0; }
check "hand-written Contributors section flagged" 1 "$(has_section '## Contributors
- @alice')"
check "inline credit is not a section"            0 "$(has_section "$narrative")"

# --- which release the range starts from --------------------------------------
# This one calls the real function rather than mirroring it, because the defect
# it pins was in the selection itself and a mirror would have agreed with the
# bug. GitHub lists releases newest-first across every branch, so on a
# repository maintaining two majors the neighbour of a v12 patch is a v13
# release — and harvesting that range reports everyone who worked on v13 as an
# uncredited contributor to the v12 patch. Observed on
# a measured TYPO3 extension: v12.0.12 was compared against v13.9.0 and
# demanded credit for two people who had not touched it.
# The path is computed at runtime, so shellcheck cannot follow it without -x;
# the script guards its own main body and exits early when sourced.
# shellcheck disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/../release-notes-status.sh"

interleaved='v13.10.2
v13.10.1
v12.0.14
v13.10.0
v13.9.1
v12.0.13
v12.0.12
v13.9.0
v13.8.3
v12.0.11'

check "v12 patch follows the v12 line"   v12.0.11 "$(previous_release_on_line v12.0.12 "$interleaved")"
check "v12 minor skips the v13 releases" v12.0.13 "$(previous_release_on_line v12.0.14 "$interleaved")"
check "v13 patch follows the v13 line"   v13.10.1 "$(previous_release_on_line v13.10.2 "$interleaved")"
check "v13 minor skips the v12 releases" v13.9.1  "$(previous_release_on_line v13.10.0 "$interleaved")"
check "oldest on its line has no predecessor" "" "$(previous_release_on_line v12.0.11 "$interleaved")"

# --- what counts as crediting a contributor -----------------------------------
# Calls the real predicate. In a release body only a bare `@login` is a
# mention: `[@login](https://github.com/login)` renders as a plain link, feeds
# no avatar row and notifies nobody (references/release-process.md). A
# substring test counted that link as credit, and it also counted `@alicebob`
# and `mail@alice.dev` as credit for `@alice`.
credited() { credit_mentioned "$1" "$2" && echo 1 || echo 0; }
check "profile link is not a mention"          0 "$(credited 'Fixed by [@alice](https://github.com/alice) in #230.' @alice)"
check "bare mention at line start counts"      1 "$(credited '@alice fixed the rotation.' @alice)"
check "bare mention mid-sentence counts"       1 "$(credited 'Fixed by @alice in #230.' @alice)"
check "bare mention before punctuation counts" 1 "$(credited 'Thanks (@alice), @bob.' @alice)"
check "bare mention at end of body counts"     1 "$(credited 'Thanks @bob' @bob)"
check "bare mention beside a link counts"      1 "$(credited '[@alice](https://github.com/alice)
Also fixed by @alice.' @alice)"
check "a longer login is not the shorter one"  0 "$(credited 'Fixed by @alicebob.' @alice)"
check "a hyphenated login is not its prefix"   0 "$(credited 'Fixed by @alice-b.' @alice)"
check "an e-mail address is not a mention"     0 "$(credited 'Reported to mail@alice.dev.' @alice)"

# Structural: the credit loop must go through that predicate, or the tests above
# pin a function the check never calls.
callers=$(grep -v '^[[:space:]]*#' "$(dirname "${BASH_SOURCE[0]}")/../release-notes-status.sh" \
          | grep -cF "credit_mentioned \"\$body\" \"\$p\"" || true)
check "the credit loop calls credit_mentioned" 1 "$callers"
check "single-line repo is unaffected"   v1.2.0 "$(previous_release_on_line v1.2.1 'v1.2.1
v1.2.0
v1.1.0')"

# --- a match must survive the size of the text --------------------------------
# `printf '%s' "$big" | grep -q PAT` under `set -o pipefail` reports a FOUND
# match as a failed command whenever grep exits before printf has finished
# writing: printf takes SIGPIPE, and 141 is what pipefail propagates. It fails
# silently and in the direction that hides defects — the release whose CI
# blocks were gone read "ok — CI blocks all present", because the check found
# a block in the comparison set and the find is what broke it.
#
# Whether the writer actually dies depends on how much of the text fits in the
# 64 KB pipe buffer before grep quits, so the failure is size-dependent and the
# real case sits in the fuzzy part of that curve. Measured here, match at the
# top: 50 KB fails 2 of 20 runs, 70 KB fails 8, 100 KB fails 20 of 20. The live
# blob was 52,989 bytes with the match at byte 2,474 and flipped the verdict
# roughly one run in eight.
#
# So the probe uses 100 KB, where the pre-fix pipeline fails every single time
# and the test cannot pass by luck. It pins the construct, not the size — the
# assertion further down keeps every call site off that construct regardless of
# how large the texts happen to be.
haystack="intro line
## Software Bill of Materials
$(head -c 100000 /dev/zero | tr '\0' 'x')"

hits=0
for _ in $(seq 1 20); do
  body_has "$haystack" -F '## Software Bill of Materials' && hits=$((hits + 1))
done
check "early match in a 100 KB text is found every time" 20 "$hits"

misses=0
for _ in $(seq 1 20); do
  body_has "$haystack" -F '## Verify your download' || misses=$((misses + 1))
done
check "absent pattern reports absent every time"        20 "$misses"

# Size-independent: no call site may reintroduce the pipeline. The behavioural
# probe above only fires above the pipe buffer, and the texts this script hands
# around are smaller than that — a reintroduced `| grep -q` on a 30 KB body
# would slip past it while still flipping verdicts in the field.
pipelines=$(grep -v '^[[:space:]]*#' "$(dirname "${BASH_SOURCE[0]}")/../release-notes-status.sh" \
            | grep -c '| *grep -q' || true)
check "no pattern test goes through a pipe"            0 "$pipelines"

# --- which CI blocks the overhaul check looks for -----------------------------
# The list is read from the script, not retyped here: a copy would agree with
# whatever the check does and stay green when a section is dropped from it.
# `## Container image` is the section this pins. `release-go-app.yml` emits it
# for every run that builds a container, and it was absent from the check's list
# until a measured ldap-manager v1.7.0 overhaul destroyed it while this script
# answered `ok`. The sibling comparison cannot recover from that on its own:
# once a block is gone from every release on the line, no sibling carries it and
# the check has nothing left to compare against.
check "Container image is a CI block the check looks for" \
      1 "$(ci_block_sections | grep -cxF 'Container image')"
check "every orchestrator section is listed" \
      4 "$(ci_block_sections | grep -c .)"

# Structural: the check must READ that list rather than carry its own copy.
literal=$(grep -c 'for s in Installation' \
          "$(dirname "${BASH_SOURCE[0]}")/../release-notes-status.sh" || true)
check "the loop reads ci_block_sections, not a retyped list" 0 "$literal"

exit $fail
