#!/usr/bin/env bash
# Self-test for release-notes-status.sh body classification — no network.
#
# Pins the two shapes that must be recognised as "not finished", because both
# render on GitHub exactly like a finished release and are therefore invisible
# to review: the auto-generated "## Changes" PR-title list, and the CI stub
# body ("see CHANGELOG.md for details").
#
# Also pins the false positive found while building it: the harvest script's
# own header line contains "@mention each INLINE at their change", so extracting
# credits without dropping comment lines invents a contributor called "@mention"
# and reports every finished release as missing them.
set -uo pipefail

fail=0
check() { # check <name> <expected> <actual>
  if [ "$2" = "$3" ]; then
    printf 'ok   - %s\n' "$1"
  else
    printf 'FAIL - %s\n       expected: [%s]\n       actual:   [%s]\n' "$1" "$2" "$3"
    fail=1
  fi
}

# --- the auto-generated shape -------------------------------------------------
is_autogenerated() { # <body>
  local body="$1" n
  printf '%s' "$body" | grep -qE '^## (Changes|What'"'"'s Changed)$' || { echo 0; return; }
  n=$(printf '%s' "$body" | sed -n '/^## \(Changes\|What'"'"'s Changed\)$/,/^## /p' \
      | grep -cE '^- .*\(#[0-9]+\)$' || true)
  [ "${n:-0}" -ge 2 ] && echo 1 || echo 0
}

ci_body='## Changes
- chore: release v0.13.0 (#231)
- feat(secret): shared catalogue (#230)

## Installation'
check "CI PR-title list is autogenerated"      1 "$(is_autogenerated "$ci_body")"

narrative='## Highlights

Two pull requests, one theme. Fixed by @alice in #230.

## Installation'
check "narrative body is not autogenerated"    0 "$(is_autogenerated "$narrative")"

# A narrative that merely *mentions* a PR must not trip the heuristic.
prose='## Highlights

The rotation fix (#284) landed here.

## Installation'
check "prose citing one PR is not autogenerated" 0 "$(is_autogenerated "$prose")"

# --- the CI stub --------------------------------------------------------------
is_stub() { printf '%s' "$1" | grep -qiE 'see CHANGELOG\.md for details' && echo 1 || echo 0; }
check "CI stub body detected"                  1 "$(is_stub 'Release v1.2.3 — see CHANGELOG.md for details')"
check "narrative is not a stub"                0 "$(is_stub "$narrative")"

# --- credit extraction --------------------------------------------------------
# Mirrors the pipeline in release-notes-status.sh: drop the harvest header
# before extracting @mentions.
extract_people() { printf '%s' "$1" | grep -v '^#' | grep -oE '@[A-Za-z0-9-]+' | sort -u | tr '\n' ' '; }

harvest_output='# Contributors in v1..v2 — @mention each INLINE at their change (do not paste as a section):
code authors: @alice @bob'
check "harvest header does not become a person" "@alice @bob " "$(extract_people "$harvest_output")"

# --- hand-written Contributors section ----------------------------------------
has_section() { printf '%s' "$1" | grep -qiE '^#+ *Contributors' && echo 1 || echo 0; }
check "hand-written Contributors section flagged" 1 "$(has_section '## Contributors
- @alice')"
check "inline credit is not a section"            0 "$(has_section "$narrative")"

# --- which release the range starts from --------------------------------------
# This one calls the real function rather than mirroring it, because the defect
# it pins was in the selection itself and a mirror would have agreed with the
# bug. GitHub lists releases newest-first across every branch, so on a
# repository maintaining two majors the neighbour of a v12 patch is a v13
# release — and harvesting that range reports everyone who worked on v13 as an
# uncredited contributor to the v12 patch. Observed on
# netresearch/t3x-rte_ckeditor_image: v12.0.12 was compared against v13.9.0 and
# demanded credit for two people who had not touched it.
# The path is computed at runtime, so shellcheck cannot follow it without -x;
# the script guards its own main body and exits early when sourced.
# shellcheck disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/../release-notes-status.sh"

interleaved='v13.10.2
v13.10.1
v12.0.14
v13.10.0
v13.9.1
v12.0.13
v12.0.12
v13.9.0
v13.8.3
v12.0.11'

check "v12 patch follows the v12 line"   v12.0.11 "$(previous_release_on_line v12.0.12 "$interleaved")"
check "v12 minor skips the v13 releases" v12.0.13 "$(previous_release_on_line v12.0.14 "$interleaved")"
check "v13 patch follows the v13 line"   v13.10.1 "$(previous_release_on_line v13.10.2 "$interleaved")"
check "v13 minor skips the v12 releases" v13.9.1  "$(previous_release_on_line v13.10.0 "$interleaved")"
check "oldest on its line has no predecessor" "" "$(previous_release_on_line v12.0.11 "$interleaved")"
check "single-line repo is unaffected"   v1.2.0 "$(previous_release_on_line v1.2.1 'v1.2.1
v1.2.0
v1.1.0')"

exit $fail
