#!/usr/bin/env bash
# Self-test for release-notes-status.sh body classification — no network.
#
# Pins the two shapes that must be recognised as "not finished", because both
# render on GitHub exactly like a finished release and are therefore invisible
# to review: the auto-generated "## Changes" PR-title list, and the CI stub
# body ("see CHANGELOG.md for details").
#
# Also pins the false positive found while building it: the harvest script's
# own header line contains "@mention each INLINE at their change", so extracting
# credits without dropping comment lines invents a contributor called "@mention"
# and reports every finished release as missing them.
set -uo pipefail

fail=0
check() { # check <name> <expected> <actual>
  if [ "$2" = "$3" ]; then
    printf 'ok   - %s\n' "$1"
  else
    printf 'FAIL - %s\n       expected: [%s]\n       actual:   [%s]\n' "$1" "$2" "$3"
    fail=1
  fi
}

# --- the auto-generated shape -------------------------------------------------
is_autogenerated() { # <body>
  local body="$1" n
  printf '%s' "$body" | grep -qE '^## (Changes|What'"'"'s Changed)$' || { echo 0; return; }
  n=$(printf '%s' "$body" | sed -n '/^## \(Changes\|What'"'"'s Changed\)$/,/^## /p' \
      | grep -cE '^- .*\(#[0-9]+\)$' || true)
  [ "${n:-0}" -ge 2 ] && echo 1 || echo 0
}

ci_body='## Changes
- chore: release v0.13.0 (#231)
- feat(secret): shared catalogue (#230)

## Installation'
check "CI PR-title list is autogenerated"      1 "$(is_autogenerated "$ci_body")"

narrative='## Highlights

Two pull requests, one theme. Fixed by @alice in #230.

## Installation'
check "narrative body is not autogenerated"    0 "$(is_autogenerated "$narrative")"

# A narrative that merely *mentions* a PR must not trip the heuristic.
prose='## Highlights

The rotation fix (#284) landed here.

## Installation'
check "prose citing one PR is not autogenerated" 0 "$(is_autogenerated "$prose")"

# --- the CI stub --------------------------------------------------------------
is_stub() { printf '%s' "$1" | grep -qiE 'see CHANGELOG\.md for details' && echo 1 || echo 0; }
check "CI stub body detected"                  1 "$(is_stub 'Release v1.2.3 — see CHANGELOG.md for details')"
check "narrative is not a stub"                0 "$(is_stub "$narrative")"

# --- credit extraction --------------------------------------------------------
# Mirrors the pipeline in release-notes-status.sh: drop the harvest header
# before extracting @mentions.
extract_people() { printf '%s' "$1" | grep -v '^#' | grep -oE '@[A-Za-z0-9-]+' | sort -u | tr '\n' ' '; }

harvest_output='# Contributors in v1..v2 — @mention each INLINE at their change (do not paste as a section):
code authors: @alice @bob'
check "harvest header does not become a person" "@alice @bob " "$(extract_people "$harvest_output")"

# --- hand-written Contributors section ----------------------------------------
has_section() { printf '%s' "$1" | grep -qiE '^#+ *Contributors' && echo 1 || echo 0; }
check "hand-written Contributors section flagged" 1 "$(has_section '## Contributors
- @alice')"
check "inline credit is not a section"            0 "$(has_section "$narrative")"

exit $fail
